import type { Metadata } from 'next'
import './fonts.css'
import './globals.css'
import './zeroing.css'

export const metadata: Metadata = {
	title: 'Вёрстка сайтов по макетам Figma — HTML, CSS, React | Imrasts',
	description: 'Generated by create next app',
	metadataBase: new URL('https://imrasts.ru'),

	robots: {
		index: true,
		follow: true,
	},

	alternates: {
		canonical: '/',
	},

	openGraph: {
		url: '/',
		type: 'website',
		siteName: 'Imrasts',
		locale: 'ru_RU',

		images: [
			{
				url: '/og-image.webp',
				width: 1200,
				height: 630,
				type: 'image/webp',
				alt: 'Imrasts — адаптивная вёрстка сайтов по макетам Figma',
			},
		],
	},

	icons: {
		icon: '/favicon.svg',
	},
}

const jsonLd = {
	'@context': 'https://schema.org',
	'@graph': [
		{
			'@type': 'WebSite',
			'@id': 'https://imrasts.ru/#website',
			url: 'https://imrasts.ru/',
			name: 'Imrasts',
		},
		{
			'@type': 'ProfilePage',
			'@id': 'https://imrasts.ru/#profile',
			url: 'https://imrasts.ru/',
			name: 'Imrasts — Frontend Developer',
			mainEntity: {
				'@id': 'https://imrasts.ru/#person',
			},
		},
		{
			'@type': 'Person',
			'@id': 'https://imrasts.ru/#person',
			name: 'Imrasts',
			url: 'https://imrasts.ru/',
			jobTitle: 'Frontend Developer',
		},
	],
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body>
				{children}

				<script
					type='application/ld+json'
					dangerouslySetInnerHTML={{
						__html: JSON.stringify(jsonLd),
					}}
				/>
			</body>
		</html>
	)
}
